services:
  # db:
  #   image: postgres:alpine
  #   restart: unless-stopped
  #   env_file:
  #     - api/.env
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - fm-network
  bot:
    build:
      context: ./bot
    volumes:
      - ./bot:/app/bot
    restart: unless-stopped
    command: "python3 -m bot"
  # api:
  #   build:
  #     context: ./api
  #   volumes:
  #     - ./api:/app/api
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8000
  #   command: "sh -c 'alembic -c api/alembic.ini upgrade head && gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000'"
  #
  #   networks:
  #     - fm-network
  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - fm-network
# volumes:
#   pgdata:
#
# networks:
#   fm-network:

